version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: nest_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: nest_backend
    volumes:
      - .:/app
    restart: always
    ports:
      - '${SERVICE_PORT}:${SERVICE_PORT}'
    depends_on:
      - db
    env_file: .env

    command: sh -c "npx prisma migrate deploy && npm run seed && npm run start:dev"

volumes:
  postgres_data:
